### ISSUE TITLE
Doesn't work with Tailwind 2.1 JIT mode

### ISSUE THREAD

**Issue by thebuilder** [Acidic9/tailwind-classes-sorter#4]
Seems like the new filter plugins added to Tailwind breaks the sorting.
https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.1.0

```sh
./node_modules/tailwindcss/lib/plugins/backdropBlur.js:26
matchUtilities({
  ^

  TypeError: matchUtilities is not a function
at ./node_modules/tailwindcss/lib/plugins/backdropBlur.js:26:7
at ./node_modules/tailwindcss/lib/util/processPlugins.js:69:5
at Array.forEach (<anonymous>)
  at TWClassesSorter._default [as processPlugins] (./node_modules/tailwindcss/lib/util/processPlugins.js:63:11)
  at ./node_modules/tailwind-classes-sorter/lib/index.js:179:52
  at Array.forEach (<anonymous>)
    at TWClassesSorter.getAllSelectors (./node_modules/tailwind-classes-sorter/lib/index.js:167:14)
    at new TWClassesSorter (./node_modules/tailwind-classes-sorter/lib/index.js:47:37)
    at Object.<anonymous> (./node_modules/prettier-plugin-tailwind/lib/index.js:10:25)
      at Module._compile (node:internal/modules/cjs/loader:1092:14)
```

**Comment by thebuilder** [comment]
Looking into the code, it seems like it's caused by the new `jit` mode being enabled.

Looking at the failing line, it's only enabled when using the new `jit` mode:

```js
if (config('mode') === 'jit') {
      matchUtilities({
```

**Comment by SirMishaa** [comment]
Any up? Author doesn't seem to be active on this package

**Comment by thebuilder** [comment]
> Any up? Author doesn't seem to be active on this package

I've switched to https://github.com/francoismassart/eslint-plugin-tailwindcss - it's working really great, also with JIT. Use `--fix` on save/precommit to sort classes.
